.gitignore, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/bpd/__init__.py, src/cstar-cli/cstar/cli/bpd/awardperiod.py, src/cstar-cli/cstar/cli/bpd/citizen.py
This PR proposes to add a function in the cli to update the grace period of an award period
=> [CEN-927] Update Grace Period

.gitignore, src/cstar-cli/cstar/cli/bpd/transaction.py
This PR proposes to add a procedure to check if the acquirer file contains all the transactions ingested in the DB via the CSV connector
=> [CEN-941] Check consistency of ingested transaction  and acquirer file

src/cstar-cli/cstar/cli/bpd/citizen.py
This PR proposes to add a command to `cstar-cli` able to check if a citizen who has transactions in an acquirer file has received a cashback in a specified award period. Amount of cashback is also reported
=> [CEN-956] Add check on cashback received

src/cstar-cli/cstar/cli/bpd/awardwinner.py
This PR proposes a procedure to read jackpot winners and format a CSV according to the following document
https://docs.google.com/document/d/1aX_D6nHUQiRXy2XoOdDFIE3z03oO8eO9/edit#
=> [CEN-962] Modify query to read winners and format the resulting csv

src/cstar-cli/cstar/cli/bpd/awardwinner.py
This PR proposes to create an new action in `award winner` resource to parse csv files with wire transfers status
=> [CEN-1074] Parse CSV with transfer state

src/cstar-cli/cstar/cli/bpd/awardwinner.py
This PR proposes a way to determine if a transfer is blocked in a wrong state. 
- Fix the computation of number of occurrences of a fiscal code in a given period
- Add a function containing the logic used to asses if a wire transfer is in a wrong state
=> [CEN-1076] Add logic to mark transfers to be updated

src/cstar-cli/cstar/cli/bpd/awardwinner.py
If the IBAN of the misaligned wire matches the one reported in citizen table, the procedure will not generate a new wire transfer, even though the result of the transfer is now known to be "not ok".
In order to evaluate the real impact on users, this PR proposes to check the two ibans and report the result of the check.
=> [CEN-1101] Check if IBAN of the failed wire transfer matches the one in citizen table

src/cstar-cli/cstar/cli/bpd/awardwinner.py
This PR proposes to add a new `update_state_41` query to fix the state of misaligned wire transfers.
This problem is related to the out of order processing of encrypted files by CSV Connector component.
=> [CEN-1078] Update query for state 41 misalignment

src/cstar-cli/cstar/cli/bpd/paymentinstrument.py
This PR proposes the usage of the execute_batch() function to speed-up the bulk insertion of payment instruments via CLI.
=> [CEN-1228] Optimized bulk insertion of payment instruments

README.md, poetry.lock, pyproject.toml, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/rtd/transactionfilter.py
This PR extends the existing synthetic transactions generator, allowing their encryption.
=> [RTD-14] Tool for encrypting transaction test files

README.md, poetry.lock, pyproject.toml, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/rtd/transactionfilter.py, src/cstar-cli/cstar/cli/tae/__init__.py, src/cstar-cli/cstar/cli/tae/transactionaggregates.py, src/cstar-cli/setup.py
This PR propose the addition of a command to generate a file like the one produced by the Batch Acquirer for AdE.
The files obtained contains random valued and can be used for testing.
=> [RTD-54] Synthetic TAE aggregates generator tool

.github/PULL_REQUEST_TEMPLATE.md, .gitignore
This PR proposes the addition of a PR description template.
- add PR template.
- improve gitignore.
A PR template standardize the way one can explain its contribution to open source projects.
=> [RTD-166] Add PR template

README.md, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/sender/aggregates.py, src/cstar-cli/cstar/cli/tae/transactionaggregates.py
This PR proposes a mechanism to generate ad-hoc files for schemas and technical senders.
- add "sender" argument evaluation.
- add map of fiscal codes to technical ABI translation.
Sender that are not acquirers may have an `acquirer id` different from the sender code.
In case of technical ABI, a translation to Fiscal Code is done (like the one done in the batch service).
=> [RTD-144] Add tech schema sender

integration_check/README.md, integration_check/scripts/004-remote-file-check-UAT/script.sh
This PR proposes to ad a script to check whether the local produced file is equale to the one deposited on CSTAR's SFTP storage.
- add shell script
- update README
We need a shell script that checks the equality (order-independent) of the file produced by the batch service instance and the file stored on SFTP, downloading it from the appropriate endpoint.
This check, in the UAT, is the last of the two tests for correct installation of the batch service.
=> [RTD-231] Add deposited file check

integration_check/scripts/001-mAuth-check-UAT/script.sh, integration_check/scripts/002-API-key-check-UAT/script.sh, integration_check/scripts/004-remote-file-check-UAT/script.sh, integration_check/scripts/005-mAuth-check-PROD/script.sh, integration_check/scripts/006-API-key-check-PROD/script.sh
This PR proposes to substitute the use of curl in favour of wget.
- substitute the use curl
It is likely that the servers on which the Batch Service will run are basic and do not have the curl command available.
It is necessary to replace its use with that of wget, which is installed by default on most servers.
=> [RTD-243] Replace curl with wget

integration_check/scripts/004-remote-file-check-UAT/script.sh, src/cstar-cli/cstar/cli/tae/registryreports.py
This PR proposes to fix a refuse on the path of a script.
- change URL from DEV to UAT.
- remove VAT from ade errors.
This change align the script to UAT environment.
=> [RTD-244] Change script endpoint

README.md, install.sh, integration_check/install_Python3.9_and_Poetry.sh, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/sender/aggregates.py, src/cstar-cli/cstar/cli/tae/transactionaggregates.py
This PR proposes to add shell scripts that simplify the installation of Python and Poetry.
- add shell script to install Python and Poetry
- update install script to easily install dependencies.
To enhance user experience we needed a way to easily configure from scratch a working CLI.
This accomplish that.
=> [RTD-274] Add poetry install script

src/cstar-cli/cstar/cli/sender/aggregates.py
This PR fixes an unwanted dependency to gnupg.
- remove gnupg dependency and encryption routine.
This change avoid bloating the machine that runs the CLI.
=> [RTD-275] Remove gnupg dependency

integration_check/scripts/004-remote-file-check-UAT/script.sh
This PR proposes to add the unzip step to the remote check script.
- add unzip step.
This change is needed to adapt the sender integration script to the latest agreement on SFTP deposited files.
=> [TAE-110] Add unzip step to integration test script

.gitignore, src/test/run-all.sh
This PR proposes to ad a script to do regression tests.
- add script
- update gitingore
This changes allow us to have more control over the introduction of new features and the maintenance of existing features.
=> [RTD-319] Add regression test script

pyproject.toml
This PR proposes to bump the version from 0.0.1 to 0.0.2.
- Upgrade version
The version 0.0.2 of CLI must be released.
=> [RTD-353] bump version to 0.0.2

integration_check/certificate_configuration_template.cnf, integration_check/scripts/004-remote-file-check-UAT/script.sh
This PR proposes to fix an error given by the execution of `cut` command on some versions of bash.
- fix fields arguments in `cut`
- change misleading placeholder email address in csr template 
This PR fixes problems of integration experienced by senders using Ubuntu.
=> [RTD-437] Fix cut command

README.md, integration_check/scripts/005a-extract-ade-ack-UAT/script.sh, pyproject.toml
This PR proposes to fix an error on `cut` command given on some bash versions.
- cut argument fix
This PR prevents unwanted behaviors during sender integration.
=> [RTD-440] Fix cut command in integration script

README.md, src/cstar-cli/cstar/cli/sender/aggregates.py
This PR proposes to add translation from technical ABI to Fiscal Code for iCard.
- add iCard fake ABI to Fiscal Code translation.
- update doc 
This PR adequates testing tools to new changes.
=> [RTD-447] Add iCard FC translation in integration tool

pyproject.toml
=> [RTD-447] Bump version

integration_check/scripts/004-remote-file-check-UAT/script.sh, pyproject.toml, src/cstar-cli-core/setup.py, src/cstar-cli/cstar/cli/rtd/transactionfilter.py, src/cstar-cli/cstar/cli/sender/aggregates.py, src/cstar-cli/setup.py
This PR proposes to add a mapping from TPAY1 to Telepass Pay Fiscal Code when used as acquirer code for generating test files.
- add TPAY1 mapping.
- minor fixes.
This change allows the integration of Telepass.
=> [RTD-588] Add tpay1 fc mapping

integration_check/scripts/004-remote-file-check-UAT/script.sh, pyproject.toml, src/cstar-cli-core/setup.py, src/cstar-cli/setup.py
This PR proposes to adapt the 004 script to the new naming convention.
- change 004 integration script
- version bump
This change adequates the integration script to the new naming convention imposed by decrypter microservice.
=> [RTD-656] Adapt deposited file naming convention

src/cstar-cli/cstar/cli/sender/aggregates.py, src/cstar-cli/cstar/cli/tae/transactionaggregates.py
This PR proposes to remove randomness from terminal and merchand id generation.
- remove cryptographic hash
With this change test values for merciant and terminal id are new fixed hash of a string plus the incremental of the aggregate.
This avoids randomness during generation that would result in partition key saturation in the Aggregates Cosmos partitioned with terminal ID.
=> [RTD-797] Remove terminal id randomness

integration_check/scripts/004-remote-file-check-UAT/script.sh, pyproject.toml, src/cstar-cli-core/setup.py, src/cstar-cli/cstar/cli/sender/aggregates.py, src/cstar-cli/cstar/cli/tae/results.py, src/cstar-cli/setup.py
This PR proposes to adapt 004 integration script and i/out generatore to new naming convention imposed by Batch Service 1.3.0 .
- modify string tokenization in 004 script
- modify name tokens in expected output file.
With this change we enable the integration for newly installed Batch Service instances.
=> [RTD-916] Adapt 004 script to new naming convention

poetry.lock, pyproject.toml
This PR proposes to update some libraries.
- bump dependencies versions.
=> [RTD-1116] update poetry.lock and pyproject.toml

README.md, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/rtd/__init__.py, src/cstar-cli/cstar/cli/rtd/rtd_api.py, src/cstar-cli/cstar/cli/rtd/transactionupload.py
This PR adds new command to upload transaction file. It automatically encrypt transaction file and upload it to proper environment
=> feat: [RTD-1187] Add command to upload transactions

README.md, poetry.lock, pyproject.toml, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/idpay/idpaydataset.py
This PR proposes to add a mapping from EURON to Euronet Fiscal Code when used as acquirer code for generating test files.
- add EURON mapping.
This change allows the integration of Euronet.
=> [RTD-1342] Add IBAN generation

poetry.lock, src/cstar-cli/cstar/cli/sender/aggregates.py
This PR proposes to add a mapping from EURON to Euronet Fiscal Code when used as acquirer code for generating test files.
- add EURON mapping.
This change allows the integration of Euronet.
=> [RTD-1332] Add EURON fiscal code mapping

poetry.lock, pyproject.toml, src/cstar-cli-core/setup.py, src/cstar-cli/cstar/cli/sender/aggregates.py, src/cstar-cli/setup.py
This PR proposes to add a mapping from UBER1 to Uber Fiscal Code when used as acquirer code for generating test files.
- add UBER1 mapping.
This change allows the integration of Uber.
=> [RTD-1333] Add UBER1 fiscal code mapping

README.md, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/idpay/idpay_utilities.py, src/cstar-cli/cstar/cli/idpay/idpaydataset.py, src/cstar-cli/cstar/cli/idpay/idpaytransactions.py
This PR proposes to change arguments of IDPay transactions commands.
- add start_date and end_date arguments.
Dates of transactions will be picked randomly among the time window of the 2 new arguments.
This helps finding bugs related to dates.
=> feat: [RTD-1351] Randomize transactions timestamp for IDPay commands

poetry.lock, pyproject.toml, src/cstar-cli-core/setup.py, src/cstar-cli/cstar/cli/idpay/idpay_utilities.py, src/cstar-cli/cstar/cli/rtd/transactionfilter.py, src/cstar-cli/cstar/cli/sender/aggregates.py, src/cstar-cli/cstar/cli/tae/results.py, src/cstar-cli/cstar/cli/tae/transactionaggregates.py, src/cstar-cli/setup.py
This PR enforces line feed as line separator in csv.
- specify line terminator in Pandas to_csv function.
With this change we grant the generation of csv as expected by the Batch Service.
=> fix: [RTD-1665] Enforce line feed separator

README.md, pyproject.toml, src/cstar-cli-core/setup.py, src/cstar-cli/cstar/cli/idpay/idpaydataset.py, src/cstar-cli/cstar/cli/idpay/idpaytransactions.py, src/cstar-cli/cstar/cli/rtd/transactionfilter.py, src/cstar-cli/cstar/cli/rtd/transactionupload.py, src/cstar-cli/setup.py
=> Release 0.0.13

src/cstar-cli/cstar/cli/idpay/pdv_api.py
=> feat: [IDP-1568] tokenize cf with pdv 

pyproject.toml, src/cstar-cli-core/setup.py, src/cstar-cli/cstar/cli/wallet/contracts.py
Add missing header fields in contracts export generation.
=> fix: [CHK-2920] Add fields to header

README.md, src/cstar-cli-core/cstar/cli/core/parser.py, src/cstar-cli/cstar/cli/wallet/contracts.py
With this change we can generate every combination of action and outcome possible.
=> fix: [CHK-2922] Generate contracts with action CREATE and import outcome KO
